// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'eu-central-1',
    aws_cognito_identity_pool_id:
        'eu-central-1:c113e57a-418e-4871-b294-d32eab035fa8',
    aws_cognito_region: 'eu-central-1',
    aws_user_pools_id: 'eu-central-1_0kaMdQISI',
    aws_user_pools_web_client_id: '5pv80jc363tnh04h9j3odakh9m',
    oauth: {}
}

export default awsmobile
